/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_kevliu_jni_test_TestJniNative */

#ifndef _Included_com_example_kevliu_jni_test_TestJniNative
#define _Included_com_example_kevliu_jni_test_TestJniNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_kevliu_jni_test_TestJniNative
 * Method:    first
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_kevliu_jni_1test_TestJniNative_first
  (JNIEnv *, jclass);

/*
 * Class:     com_example_kevliu_jni_test_TestJniNative
 * Method:    second
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_kevliu_jni_1test_TestJniNative_second
  (JNIEnv *, jclass);

/*
 * Class:     com_example_kevliu_jni_test_TestJniNative
 * Method:    third
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_kevliu_jni_1test_TestJniNative_third
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
